apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ name }}"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      "app.kubernetes.io/name": "{{ name }}"
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": "{{ name }}"
        "app.kubernetes.io/version": "{{ version }}"
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      imagePullSecrets:
      - name: k8s-ecr-login-renew-docker-secret
      containers:
      - name: "{{ name }}"
        image: "456087932636.dkr.ecr.us-west-2.amazonaws.com/kube-video/video:{{version}}"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        livenessProbe:
          httpGet:
            path: /livez
            port: {{ flask_port }}
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 1
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ flask_port }}
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5
        env:
        - name: DEBUG
          value: "{{ debug }}"
        - name: NAME
          value: "{{ name }}"
        - name: PIPELINE
          value: "{{ pipeline }}"
        - name: NGINX_STATS_URL
          value: "{{ nginx_stats_url }}"
        - name: MONITOR_STARTUP_DELAY
          value: "{{ monitor_startup_delay }}"
        - name: MONITOR_POLL_INTERVAL
          value: "{{ monitor_poll_interval }}"
        - name: VERSION
          value: "{{ version }}"
        - name: FLASK_PORT
          value: "{{ flask_port }}"
        - name: OTEL_SERVICE_NAME
          value: "{{ name }}"
        - name: OTEL_METRICS_EXPORTER
          value: "{{ otel_metrics_exporter }}"
        - name: OTEL_METRIC_EXPORT_INTERVAL
          value: "{{ otel_exporter_interval }}"
        - name: OTEL_METRIC_EXPORT_TIMEOUT
          value: "{{ otel_exporter_timeout }}"
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: '{{ otel_exporter_otlp_metrics_endpoint }}'
        - name: OTEL_EXPORTER_OTLP_METRICS_TIMEOUT
          value: '{{ otel_exporter_otlp_metrics_timeout }}'
        - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
          value: '{{ otel_exporter_otlp_metrics_protocol }}'
        - name: OTEL_EXPORTER_OTLP_METRICS_INSECURE
          value: "{{ otel_exporter_otlp_metrics_insecure }}"
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: KUBERNETES_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace