apiVersion: v1
kind: Service
metadata:
  name: "{{ name }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ flask_port }}
      targetPort: {{ flask_port }}
      name: http
  selector:
    "app.kubernetes.io/name": "{{ name }}"