apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: k8s-ecr-login-renew-docker-secret
      containers:
        - name: nginx
          image: 456087932636.dkr.ecr.us-west-2.amazonaws.com/kube-video/nginx:1.3.0
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - name: rtmp
              containerPort: 1935
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: hls
              mountPath: /tmp/api/hls/v1
              readOnly: false
          env:
          - name: OPERATINGSITE
            value: "global"
      volumes:
      - name: hls
        emptyDir:
          sizeLimit: 1Gi
