apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: video

commonLabels:
  app.kubernetes.io/name: nginx
  app.kubernetes.io/component: web-server
  app.kubernetes.io/part-of: video

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/version: 1.3.0

resources:
  - deployment.yaml
  - service.yaml
