apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: rtmp
    port: 1935
    targetPort: 1935
    nodePort: 30160
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30150
