# this is an example deployment for a video instance
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalon-koa-dev-c2-internal
  labels:
    app.kubernetes.io/component: video
    app.kubernetes.io/instance: video.avalon-koa-dev-c2-internal
    app.kubernetes.io/managed-by: foreveroceans-techonology-team
    app.kubernetes.io/name: avalon-koa-dev-c2-internal
    app.kubernetes.io/part-of: foreveroceans
    app.kubernetes.io/version: "1.2.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: avalon-koa-dev-c2-internal
  template:
    metadata:
      labels:
        app.kubernetes.io/component: video
        app.kubernetes.io/instance: video.avalon-koa-dev-c2-internal
        app.kubernetes.io/managed-by: foreveroceans-techonology-team
        app.kubernetes.io/name: avalon-koa-dev-c2-internal
        app.kubernetes.io/part-of: foreveroceans
        app.kubernetes.io/version: "1.2.0"
    spec:
      # nodeName: ip-10-0-3-195.us-west-2.compute.internal
      containers:
        - name: avalon-koa-dev-c2-internal
          image: 456087932636.dkr.ecr.us-west-2.amazonaws.com/kube-video/video:1.2.0
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: DEBUG
              value: 'False'
            - name: NAME
              value: avalon-koa-dev-c2-internal
            - name: PIPELINE
              value: ' rtspsrc location=rtsp://10.0.9.150/axis-media/media.amp?streamprofile=fo-live-stream-1&camera=1      port-range=32766-32767       name=avalon-koa-dev-c2-internal             latency=0 drop-on-latency=true udp-reconnect=true ntp-sync=true             do-rtsp-keep-alive=true protocols=udp port-range=53488-53489 timeout=10000000         ! rtph264depay ! h264parse ! flvmux streamable=true         ! rtmpsink location=rtmp://nginx.video.svc.cluster.local:1935/live/avalon-koa-dev-c2-internal '
            - name: NGINX_STATS_URL
              value: http://nginx.video.svc.cluster.local:8080/stat
            - name: MONITOR_STARTUP_DELAY
              value: '60'
            - name: MONITOR_POLL_INTERVAL
              value: '60'
            - name: VERSION
              value: None
            - name: OTEL_SERVICE_NAME
              value: avalon-koa-dev-c2-internal
            - name: OTEL_METRICS_EXPORTER
              value: otlp,console
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: '5000'
            - name: OTEL_METRIC_EXPORT_TIMEOUT
              value: '2500'
            - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
              value: telemetry-collector.opentelemetry.svc.cluster.local:4317
            - name: OTEL_EXPORTER_OTLP_METRICS_TIMEOUT
              value: '2500'
            - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
              value: grpc
            - name: OTEL_EXPORTER_OTLP_METRICS_INSECURE
              value: 'true'
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: KUBERNETES_POD_UID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.uid
            - name: KUBERNETES_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 300m
              memory: 100Mi
            requests:
              cpu: 150m
              memory: 50Mi
          livenessProbe:
            httpGet:
              path: /livez
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /readyz
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      securityContext: {}
      imagePullSecrets:
        - name: k8s-ecr-login-renew-docker-secret
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
