apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: video-operator
rules:
  - apiGroups: [foreveroceans.io]
    resources: ["videos", "videos/status"]
    verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
  
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]

  - apiGroups: [""]
    resources: [events, services, namespaces]
    verbs: [create, list, watch]

  - apiGroups: [admissionregistration.k8s.io]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: ["get", "list", "create", "patch", "watch"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]