apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: video

commonLabels:
  app.kubernetes.io/name: video-operator
  app.kubernetes.io/component: operator
  app.kubernetes.io/part-of: video

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/version: 1.3.0


resources:
  - cluster-role.yaml
  - service-account.yaml
  - cluster-role-binding.yaml
  - deployment.yaml
  - service.yaml
