apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op:  replace
        path: /spec/template/spec/containers/0/env/0
        value:
          name: OPERATINGSITE
          value: devglobal
    target:
      kind: Deployment
      name: nginx

